import { ReactElement } from "react";
import { useStoreState } from "../../model/helpers/hooks";
import HomeInterfaceSwitch from "./HomeInterfaceSwitch";
import { TaskListItemHome } from "../task-list/TaskListItem";
import MemberListItemTop from "../members/MemberListItemTop";
import withSlideIn from "../hoc/withSlideIn";

import { ITaskState } from "../../model/model.typing";

const tasks: Array<ITaskState & { _id: string }> = [
  {
    _id: "6009a38cdb2a50046c39b872",
    id: "dGFzazo3NDM1",
    databaseId: 7435,
    title: "121Тригонометрический тройной интеграл: методология и особенности",
    content: "",
    slug: "trigonometricheskij-trojnoj-integral-metodologiya-i-osobennosti",
    date: "2020-12-23 08:27:57",
    dateGmt: "2020-12-23 05:27:57",
    viewsCount: 0,
    doerCandidatesCount: 0,
    status: "publish",
    pemalink:
      "http://localhost:9000/tasks/trigonometricheskij-trojnoj-integral-metodologiya-i-osobennosti/",
    pemalinkPath: "/tasks/trigonometricheskij-trojnoj-integral-metodologiya-i-osobennosti/",
    tags: {
      nodes: [
        {
          term_id: 186,
          name: "Маркетинг и коммуникации",
          slug: "marketing",
          term_group: 0,
          term_taxonomy_id: 187,
          taxonomy: "post_tag",
          description: "",
          parent: 0,
          count: 1,
          filter: "raw",
        },
      ],
    },
    ngoTaskTags: {
      nodes: [
        {
          term_id: 252,
          name: "Раздельный сбор",
          slug: "separate-collection",
          term_group: 0,
          term_taxonomy_id: 253,
          taxonomy: "nko_task_tag",
          description: "",
          parent: 227,
          count: 1,
          filter: "raw",
        },
      ],
    },
    rewardTags: {
      nodes: [
        {
          term_id: 17,
          name: "Упоминание на сайте и/или в соцсетях",
          slug: "upominanie-na-sajte",
          term_group: 0,
          term_taxonomy_id: 17,
          taxonomy: "reward",
          description: "",
          parent: 0,
          count: 16,
          filter: "raw",
        },
      ],
    },
    author: {
      id: "dXNlcjo3NQ==",
      fullName: "Денис Геннадьевич Чернятьев",
      name: "denisch",
      username: "denisch",
      firstName: "Денис Геннадьевич",
      lastName: "Чернятьев",
      memberRole: "Супергерой",
      itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
      itvAvatarFile: {
        mediaItemUrl:
          "http://localhost:9000/wp-content/uploads/2020/09/1bbed88969621560ce2818ca701-3.jpg",
        databaseId: 7346,
      },
      authorReviewsCount: "11",
      solvedTasksCount: 7,
      doerReviewsCount: 6,
      totalReviewsCount: 17,
      isPartner: true,
      isPasekaMember: true,
      organizationName: "Теплица социальных технологий - творим добро",
      organizationDescription:
        "Неопределенный интеграл продуцирует возрастающий минимум. Асимптота очевидна не для всех. Ортогональный определитель, конечно, определяет абстрактный интеграл от функции, имеющий конечный разрыв. Матожидание, не вдаваясь в подробности, непосредственно концентрирует нормальный контрпример.",
      organizationLogo: "",
      organizationLogoFile: null,
      cover: "",
      coverFile: {
        mediaItemUrl:
          "http://localhost:9000/wp-content/uploads/2020/09/0e261687005a438f100d19f55bba73d4_full.jpg",
        databaseId: 7347,
      },
      profileURL: "http://localhost:9000/members/denisch-slug",
      isAdmin: true,
      thankyouCount: "18",
      skype: "dench888",
      twitter: "twitter333",
      facebook: "",
      vk: "",
      instagram: "insta222",
      telegram: "denischTELEGA",
      phone: "+79097790111",
      organizationSite: "",
      xp: "1523",
      itvRole: "doer",
      isHybrid: true,
      slug: "denisch-slug",
      nicename: "denisch-slug",
    },
    isApproved: false,
    cover: null,
    coverImgSrcLong: "",
    deadline: "2020-12-31 00:00:00",
  },
  {
    _id: "6009a38cdb2a50046c39b873",
    id: "dGFzazo3NDM0",
    databaseId: 7434,
    title: "Абстрактный график функции многих переменных в XXI веке",
    content: "",
    slug: "abstraktnyj-grafik-funktsii-mnogih-peremennyh-v-xxi-veke",
    date: "2020-12-23 08:26:43",
    dateGmt: "2020-12-23 05:26:43",
    viewsCount: 0,
    doerCandidatesCount: 0,
    status: "publish",
    pemalink:
      "http://localhost:9000/tasks/abstraktnyj-grafik-funktsii-mnogih-peremennyh-v-xxi-veke/",
    pemalinkPath: "/tasks/abstraktnyj-grafik-funktsii-mnogih-peremennyh-v-xxi-veke/",
    tags: {
      nodes: [
        {
          term_id: 194,
          name: "Базы данных",
          slug: "database",
          term_group: 0,
          term_taxonomy_id: 195,
          taxonomy: "post_tag",
          description: "",
          parent: 184,
          count: 65,
          filter: "raw",
        },
      ],
    },
    ngoTaskTags: {
      nodes: [
        {
          term_id: 244,
          name: "Градозащита",
          slug: "city-protection",
          term_group: 0,
          term_taxonomy_id: 245,
          taxonomy: "nko_task_tag",
          description: "",
          parent: 226,
          count: 1,
          filter: "raw",
        },
      ],
    },
    rewardTags: {
      nodes: [
        {
          term_id: 113,
          name: "Сувенир",
          slug: "gift",
          term_group: 0,
          term_taxonomy_id: 117,
          taxonomy: "reward",
          description: "",
          parent: 0,
          count: 3,
          filter: "raw",
        },
      ],
    },
    author: {
      id: "dXNlcjo3NQ==",
      fullName: "Денис Геннадьевич Чернятьев",
      name: "denisch",
      username: "denisch",
      firstName: "Денис Геннадьевич",
      lastName: "Чернятьев",
      memberRole: "Супергерой",
      itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
      itvAvatarFile: {
        mediaItemUrl:
          "http://localhost:9000/wp-content/uploads/2020/09/1bbed88969621560ce2818ca701-3.jpg",
        databaseId: 7346,
      },
      authorReviewsCount: "11",
      solvedTasksCount: 7,
      doerReviewsCount: 6,
      totalReviewsCount: 17,
      isPartner: true,
      isPasekaMember: true,
      organizationName: "Теплица социальных технологий - творим добро",
      organizationDescription:
        "Неопределенный интеграл продуцирует возрастающий минимум. Асимптота очевидна не для всех. Ортогональный определитель, конечно, определяет абстрактный интеграл от функции, имеющий конечный разрыв. Матожидание, не вдаваясь в подробности, непосредственно концентрирует нормальный контрпример.",
      organizationLogo: "",
      organizationLogoFile: null,
      cover: "",
      coverFile: {
        mediaItemUrl:
          "http://localhost:9000/wp-content/uploads/2020/09/0e261687005a438f100d19f55bba73d4_full.jpg",
        databaseId: 7347,
      },
      profileURL: "http://localhost:9000/members/denisch",
      isAdmin: true,
      thankyouCount: "18",
      skype: "dench888",
      twitter: "twitter333",
      facebook: "",
      vk: "",
      instagram: "insta222",
      telegram: "denischTELEGA",
      phone: "+79097790111",
      organizationSite: "",
      xp: "1523",
      itvRole: "doer",
      isHybrid: true,
      slug: "denisch-slug",
      nicename: "denisch-slug",
    },
    isApproved: false,
    cover: null,
    coverImgSrcLong: "",
    deadline: "2020-12-26 00:00:00",
  },
  {
    _id: "6009a38cdb2a50046c39b874",
    id: "dGFzazo3NDMz",
    databaseId: 7433,
    title: "Комплексный неопределенный интеграл: гипотеза и теории",
    content: "",
    slug: "kompleksnyj-neopredelennyj-integral-gipoteza-i-teorii",
    date: "2020-12-23 08:25:22",
    dateGmt: "2020-12-23 05:25:22",
    viewsCount: 0,
    doerCandidatesCount: 0,
    status: "publish",
    pemalink: "http://localhost:9000/tasks/kompleksnyj-neopredelennyj-integral-gipoteza-i-teorii/",
    pemalinkPath: "/tasks/kompleksnyj-neopredelennyj-integral-gipoteza-i-teorii/",
    tags: {
      nodes: [
        {
          term_id: 221,
          name: "Google Grants",
          slug: "google-grants",
          term_group: 0,
          term_taxonomy_id: 222,
          taxonomy: "post_tag",
          description: "",
          parent: 186,
          count: 4,
          filter: "raw",
        },
      ],
    },
    ngoTaskTags: {
      nodes: [
        {
          term_id: 250,
          name: "Биоразнообразие",
          slug: "biodiversity",
          term_group: 0,
          term_taxonomy_id: 251,
          taxonomy: "nko_task_tag",
          description: "",
          parent: 227,
          count: 2,
          filter: "raw",
        },
      ],
    },
    rewardTags: {
      nodes: [
        {
          term_id: 112,
          name: "Сcылка на ваш сайт",
          slug: "link",
          term_group: 0,
          term_taxonomy_id: 116,
          taxonomy: "reward",
          description: "",
          parent: 0,
          count: 15,
          filter: "raw",
        },
      ],
    },
    author: {
      id: "dXNlcjo3NQ==",
      fullName: "Денис Геннадьевич Чернятьев",
      name: "denisch",
      username: "denisch",
      firstName: "Денис Геннадьевич",
      lastName: "Чернятьев",
      memberRole: "Супергерой",
      itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
      itvAvatarFile: {
        mediaItemUrl:
          "http://localhost:9000/wp-content/uploads/2020/09/1bbed88969621560ce2818ca701-3.jpg",
        databaseId: 7346,
      },
      authorReviewsCount: "11",
      solvedTasksCount: 7,
      doerReviewsCount: 6,
      totalReviewsCount: 17,
      isPartner: true,
      isPasekaMember: true,
      organizationName: "Теплица социальных технологий - творим добро",
      organizationDescription:
        "Неопределенный интеграл продуцирует возрастающий минимум. Асимптота очевидна не для всех. Ортогональный определитель, конечно, определяет абстрактный интеграл от функции, имеющий конечный разрыв. Матожидание, не вдаваясь в подробности, непосредственно концентрирует нормальный контрпример.",
      organizationLogo: "",
      organizationLogoFile: null,
      cover: "",
      coverFile: {
        mediaItemUrl:
          "http://localhost:9000/wp-content/uploads/2020/09/0e261687005a438f100d19f55bba73d4_full.jpg",
        databaseId: 7347,
      },
      profileURL: "http://localhost:9000/members/denisch",
      isAdmin: true,
      thankyouCount: "18",
      skype: "dench888",
      twitter: "twitter333",
      facebook: "",
      vk: "",
      instagram: "insta222",
      telegram: "denischTELEGA",
      phone: "+79097790111",
      organizationSite: "",
      xp: "1523",
      itvRole: "doer",
      isHybrid: true,
      slug: "denisch-slug",
      nicename: "denisch-slug",
    },
    isApproved: false,
    cover: null,
    coverImgSrcLong: "",
    deadline: "2021-01-06 00:00:00",
  },
  {
    _id: "6009a38cdb2a50046c39b875",
    id: "dGFzazo3NDMy",
    databaseId: 7432,
    title: "Косвенный предел последовательности: гипотеза и теории",
    content: "",
    slug: "kosvennyj-predel-posledovatelnosti-gipoteza-i-teorii",
    date: "2020-12-23 08:19:30",
    dateGmt: "2020-12-23 05:19:30",
    viewsCount: 0,
    doerCandidatesCount: 0,
    status: "publish",
    pemalink: "http://localhost:9000/tasks/kosvennyj-predel-posledovatelnosti-gipoteza-i-teorii/",
    pemalinkPath: "/tasks/kosvennyj-predel-posledovatelnosti-gipoteza-i-teorii/",
    tags: {
      nodes: [
        {
          term_id: 121,
          name: "SMM",
          slug: "smm",
          term_group: 0,
          term_taxonomy_id: 126,
          taxonomy: "post_tag",
          description: "",
          parent: 186,
          count: 140,
          filter: "raw",
        },
      ],
    },
    ngoTaskTags: {
      nodes: [
        {
          term_id: 263,
          name: "Борьба с бедностью",
          slug: "fighting-poverty",
          term_group: 0,
          term_taxonomy_id: 264,
          taxonomy: "nko_task_tag",
          description: "",
          parent: 229,
          count: 2,
          filter: "raw",
        },
      ],
    },
    rewardTags: {
      nodes: [
        {
          term_id: 115,
          name: "Коллективное селфи",
          slug: "selfie",
          term_group: 0,
          term_taxonomy_id: 119,
          taxonomy: "reward",
          description: "",
          parent: 0,
          count: 2,
          filter: "raw",
        },
      ],
    },
    author: {
      id: "dXNlcjo3NQ==",
      fullName: "Денис Геннадьевич Чернятьев",
      name: "denisch",
      username: "denisch",
      firstName: "Денис Геннадьевич",
      lastName: "Чернятьев",
      memberRole: "Супергерой",
      itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
      itvAvatarFile: {
        mediaItemUrl:
          "http://localhost:9000/wp-content/uploads/2020/09/1bbed88969621560ce2818ca701-3.jpg",
        databaseId: 7346,
      },
      authorReviewsCount: "11",
      solvedTasksCount: 7,
      doerReviewsCount: 6,
      totalReviewsCount: 17,
      isPartner: true,
      isPasekaMember: true,
      organizationName: "Теплица социальных технологий - творим добро",
      organizationDescription:
        "Неопределенный интеграл продуцирует возрастающий минимум. Асимптота очевидна не для всех. Ортогональный определитель, конечно, определяет абстрактный интеграл от функции, имеющий конечный разрыв. Матожидание, не вдаваясь в подробности, непосредственно концентрирует нормальный контрпример.",
      organizationLogo: "",
      organizationLogoFile: null,
      cover: "",
      coverFile: {
        mediaItemUrl:
          "http://localhost:9000/wp-content/uploads/2020/09/0e261687005a438f100d19f55bba73d4_full.jpg",
        databaseId: 7347,
      },
      profileURL: "http://localhost:9000/members/denisch",
      isAdmin: true,
      thankyouCount: "18",
      skype: "dench888",
      twitter: "twitter333",
      facebook: "",
      vk: "",
      instagram: "insta222",
      telegram: "denischTELEGA",
      phone: "+79097790111",
      organizationSite: "",
      xp: "1523",
      itvRole: "doer",
      isHybrid: true,
      slug: "denisch-slug",
      nicename: "denisch-slug",
    },
    isApproved: false,
    cover: null,
    coverImgSrcLong: "",
    deadline: "2021-01-06 00:00:00",
  },
  {
    _id: "6009a38cdb2a50046c39b876",
    id: "dGFzazo3MjA2",
    databaseId: 7206,
    title: "Что-то новое",
    content: "",
    slug: "chto-to-novoe",
    date: "2020-12-09 16:27:01",
    dateGmt: "2020-12-09 13:27:01",
    viewsCount: 2,
    doerCandidatesCount: 1,
    status: "publish",
    pemalink: "http://localhost:9000/tasks/chto-to-novoe/",
    pemalinkPath: "/tasks/chto-to-novoe/",
    tags: {
      nodes: [
        {
          term_id: 204,
          name: "Брендбук",
          slug: "brandbook",
          term_group: 0,
          term_taxonomy_id: 205,
          taxonomy: "post_tag",
          description: "",
          parent: 185,
          count: 361,
          filter: "raw",
        },
      ],
    },
    ngoTaskTags: {
      nodes: [
        {
          term_id: 225,
          name: "Помогать людям в беде",
          slug: "help-people",
          term_group: 0,
          term_taxonomy_id: 226,
          taxonomy: "nko_task_tag",
          description: "",
          parent: 0,
          count: 35,
          filter: "raw",
        },
      ],
    },
    rewardTags: {
      nodes: [
        {
          term_id: 116,
          name: "Небольшой гонорар",
          slug: "symbol",
          term_group: 0,
          term_taxonomy_id: 120,
          taxonomy: "reward",
          description: "",
          parent: 0,
          count: 18,
          filter: "raw",
        },
      ],
    },
    author: {
      id: "dXNlcjo3NQ==",
      fullName: "Денис Геннадьевич Чернятьев",
      name: "denisch",
      username: "denisch",
      firstName: "Денис Геннадьевич",
      lastName: "Чернятьев",
      memberRole: "Супергерой",
      itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
      itvAvatarFile: {
        mediaItemUrl:
          "http://localhost:9000/wp-content/uploads/2020/09/1bbed88969621560ce2818ca701-3.jpg",
        databaseId: 7346,
      },
      authorReviewsCount: "11",
      solvedTasksCount: 7,
      doerReviewsCount: 6,
      totalReviewsCount: 17,
      isPartner: true,
      isPasekaMember: true,
      organizationName: "Теплица социальных технологий - творим добро",
      organizationDescription:
        "Неопределенный интеграл продуцирует возрастающий минимум. Асимптота очевидна не для всех. Ортогональный определитель, конечно, определяет абстрактный интеграл от функции, имеющий конечный разрыв. Матожидание, не вдаваясь в подробности, непосредственно концентрирует нормальный контрпример.",
      organizationLogo: "",
      organizationLogoFile: null,
      cover: "",
      coverFile: {
        mediaItemUrl:
          "http://localhost:9000/wp-content/uploads/2020/09/0e261687005a438f100d19f55bba73d4_full.jpg",
        databaseId: 7347,
      },
      profileURL: "http://localhost:9000/members/denisch",
      isAdmin: true,
      thankyouCount: "18",
      skype: "dench888",
      twitter: "twitter333",
      facebook: "",
      vk: "",
      instagram: "insta222",
      telegram: "denischTELEGA",
      phone: "+79097790111",
      organizationSite: "",
      xp: "1523",
      itvRole: "doer",
      isHybrid: true,
      slug: "denisch-slug",
      nicename: "denisch-slug",
    },
    isApproved: false,
    cover: null,
    coverImgSrcLong: "",
    deadline: "2020-12-23 00:00:00",
  },
  {
    _id: "6009a38cdb2a50046c39b877",
    id: "dGFzazo3Mzg5",
    databaseId: 7389,
    title: "asdfasdfdsafasdf asdf asdf",
    content: "",
    slug: "asdfasdfdsafasdf-asdf-asdf",
    date: "2020-11-19 15:32:05",
    dateGmt: "2020-11-19 12:32:05",
    viewsCount: 0,
    doerCandidatesCount: 0,
    status: "publish",
    pemalink: "http://localhost:9000/tasks/asdfasdfdsafasdf-asdf-asdf/",
    pemalinkPath: "/tasks/asdfasdfdsafasdf-asdf-asdf/",
    tags: {
      nodes: [
        {
          term_id: 129,
          name: "WordPress",
          slug: "wordpress",
          term_group: 0,
          term_taxonomy_id: 81,
          taxonomy: "post_tag",
          description: "",
          parent: 184,
          count: 641,
          filter: "raw",
        },
      ],
    },
    ngoTaskTags: {
      nodes: [
        {
          term_id: 263,
          name: "Борьба с бедностью",
          slug: "fighting-poverty",
          term_group: 0,
          term_taxonomy_id: 264,
          taxonomy: "nko_task_tag",
          description: "",
          parent: 229,
          count: 2,
          filter: "raw",
        },
      ],
    },
    rewardTags: {
      nodes: [
        {
          term_id: 112,
          name: "Сcылка на ваш сайт",
          slug: "link",
          term_group: 0,
          term_taxonomy_id: 116,
          taxonomy: "reward",
          description: "",
          parent: 0,
          count: 15,
          filter: "raw",
        },
      ],
    },
    author: {
      id: "dXNlcjoxNzEy",
      fullName: "Тест Аксиомович",
      name: "test",
      username: "test",
      firstName: "Тест",
      lastName: "Аксиомович",
      memberRole: "Супергерой",
      itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
      itvAvatarFile: null,
      authorReviewsCount: "2",
      solvedTasksCount: 5,
      doerReviewsCount: 14,
      totalReviewsCount: 16,
      isPartner: false,
      isPasekaMember: false,
      organizationName: "",
      organizationDescription: "",
      organizationLogo: "",
      organizationLogoFile: null,
      cover: "",
      coverFile: null,
      profileURL: "http://localhost:9000/members/test",
      isAdmin: false,
      thankyouCount: "1",
      skype: "",
      twitter: "",
      facebook: "",
      vk: "",
      instagram: "",
      telegram: "",
      phone: "",
      organizationSite: "",
      xp: "2775",
      itvRole: "doer",
      isHybrid: true,
      slug: "test",
      nicename: "test",
    },
    isApproved: false,
    cover: null,
    coverImgSrcLong: "",
    deadline: "2020-12-03 00:00:00",
  },
];

const users: any = [
  {
    id: "dXNlcjoxODQw",
    slug: "gusev",
    itvAvatar: "http://localhost:9000/wp-content/uploads/2019/12/itv-180x180.jpeg",
    fullName: "Александр Гусев",
    username: "gusev",
    memberRole: "Супергерой",
    organizationName: "&#34;Бизнес-Ателье&#34;",
    organizationDescription: "- Разработка сайтов",
    rating: 4.9921259842519685,
    reviewsCount: 124,
    xp: 16021,
    solvedProblems: 128,
    facebook: "facebook.com/AlexanGusev",
    instagram: "",
    vk: "https://vk.com/AlexanGusev",
    organizationSite: "https://business-atelier.ru",
    registrationDate: 1441670400,
  },
  {
    id: "dXNlcjoyNjc=",
    slug: "liam",
    itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
    fullName: "Алексей Клёсов",
    username: "liam",
    memberRole: "Супергерой",
    organizationName: "",
    organizationDescription: "",
    rating: 4.967213114754099,
    reviewsCount: 63,
    xp: 12025,
    solvedProblems: 84,
    facebook: "https://www.facebook.com/klylex",
    instagram: "",
    vk: "https://vk.com/klylex",
    organizationSite: "",
    registrationDate: 1413590400,
  },
  {
    id: "dXNlcjoyMjg0",
    slug: "titov",
    itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
    fullName: "Андрей Титов",
    username: "titov",
    memberRole: "Супергерой",
    organizationName: "Андрей Титов",
    organizationDescription: "",
    rating: 4.7407407407407405,
    reviewsCount: 27,
    xp: 9299,
    solvedProblems: 43,
    facebook: "https://www.facebook.com/titov.andrei",
    instagram: "",
    vk: "https://vk.com/titov_andrei",
    organizationSite: "http://localhost:9000/members/titov",
    registrationDate: 1453161600,
  },
  {
    id: "dXNlcjo5MDI=",
    slug: "citycelebrity",
    itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
    fullName: "Сайт Ситиселебрити",
    username: "citycelebrity",
    memberRole: "Супергерой",
    organizationName: "",
    organizationDescription: "",
    rating: 5,
    reviewsCount: 15,
    xp: 5422,
    solvedProblems: 31,
    facebook: "http://www.facebook.com/Citycelebrity.ru",
    instagram: "",
    vk: "http://vk.com/club15502069",
    organizationSite: "http://citycelebrity.ru",
    registrationDate: 1426723200,
  },
  {
    id: "dXNlcjoyMzcw",
    slug: "diana_sar",
    itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
    fullName: "Diana Sar",
    username: "diana_sar",
    memberRole: "Супергерой",
    organizationName: "Freelance",
    organizationDescription: "",
    rating: 5,
    reviewsCount: 34,
    xp: 5053,
    solvedProblems: 38,
    facebook: "https://www.facebook.com/profile.php?id=100006747755695",
    instagram: "",
    vk: "https://vk.com/feed",
    organizationSite: "http://localhost:9000/members/diana_sar",
    registrationDate: 1455321600,
  },
  {
    id: "dXNlcjoxNjkz",
    slug: "elizaveta",
    itvAvatar: "http://localhost:9000/wp-content/themes/tstsite/assets/img/temp-avatar.png",
    fullName: "Елизавета Побережная",
    username: "elizaveta",
    memberRole: "Супергерой",
    organizationName: "Елизавета",
    organizationDescription: "",
    rating: 4.6875,
    reviewsCount: 16,
    xp: 3903,
    solvedProblems: 25,
    facebook: "",
    instagram: "",
    vk: "",
    organizationSite: "",
    registrationDate: 1438128000,
  },
];

const HomeTaskTop: React.FunctionComponent = (): ReactElement => {
  return (
    <section className="home-top">
      <h3 className="home-top__title home-title">Открытые задачи</h3>
      <HomeInterfaceSwitch />
      <div className="home-top__list">
        <div className="task-list">
          {tasks.map((task, i) =>
            withSlideIn({
              component: TaskListItemHome,
              from: i % 2 ? "right" : "left",
              fullWidth: false,
              key: task._id,
              ...task,
            })
          )}
        </div>
      </div>
      <button className="home-top__more btn btn_link" type="button">
        Все задачи
      </button>
    </section>
  );
};

const HomeUserTop: React.FunctionComponent = (): ReactElement => {
  return (
    <section className="home-top">
      <h3 className="home-top__title home-title">Десятки волонтёров готовы вам помочь</h3>
      <HomeInterfaceSwitch />
      <div className="home-top__list">
        <div className="volunteer-list">
          {users.map((user, i) =>
            withSlideIn({
              component: MemberListItemTop,
              from: i % 2 ? "right" : "left",
              fullWidth: false,
              key: user.id,
              index: i + 1,
              member: user,
            })
          )}
        </div>
      </div>
      <button className="home-top__more btn btn_link" type="button">
        Создай задачу
      </button>
    </section>
  );
};

const HomeTop: React.FunctionComponent = (): ReactElement => {
  const template = useStoreState(state => state.components.homePage.template);

  return template === "author" ? <HomeUserTop /> : <HomeTaskTop />;
};

export default HomeTop;
