version: '3'
services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
    ports:
      - "80:80"
    links:
      - backend
      - frontend
    extra_hosts:
      - "v1.tep-itv.dench:127.0.0.1"
      - "tep-itv.dench:0.0.0.0"
      - "tep-paseka.dench:0.0.0.0"
    volumes:
      - /mnt/disk1/share/tep-itv/site:/site/tep-itv
      - /mnt/disk1/share/tep-paseka/site:/site/tep-paseka
    networks:
      default:
        aliases:
          - "tep-itv.dench"
  mongo:
    build:
      context: mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - tep-itv-mongo-data:/data/db
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
    ports:
      - "9000:9000"
    links:
      - mongo
    volumes:
      - /mnt/disk1/share/tep-itv/site:/site/tep-itv
      - /mnt/disk1/share/tep-paseka/site:/site/tep-paseka
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
    links:
      - mongo
    volumes:
      - /mnt/disk1/share/tep-itv/site:/site/tep-itv
    stdin_open: true
    tty: true
  vsftpd:
    build:
      context: vsftpd
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"
    volumes:
      - ./vsftpd/home:/home/vsftpd
      - ./vsftpd/logs:/var/log/vsftpd    
      - /mnt/disk1/share/tep-itv/site:/site/tep-itv
      - /mnt/disk1/share/tep-paseka/site:/site/tep-paseka

volumes:
  tep-itv-mongo-data:    

networks:
  default: