version: '3'
services:
  itv-nginx:
    build:
      context: itv-nginx
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
    ports:
      - "80:80"
    links:
      - itv-backend
      - itv-frontend
    extra_hosts:
      - "v1.tep-itv.dench:127.0.0.1"
      - "tep-itv.dench:0.0.0.0"
      - "tep-paseka.dench:0.0.0.0"
    volumes:
      - /mnt/disk1/share/tep-itv/site:/site/tep-itv
      - /mnt/disk1/share/tep-paseka/site:/site/tep-paseka
    networks:
      default:
        aliases:
          - "tep-itv.dench"
  itv-mongo:
    build:
      context: itv-mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - itv-mongo-data:/data/db
  itv-backend:
    build:
      context: itv-backend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
    ports:
      - "9000:9000"
    links:
      - itv-mongo
    volumes:
      - /mnt/disk1/share/tep-itv/site:/site/tep-itv
      - /mnt/disk1/share/tep-paseka/site:/site/tep-paseka
  itv-frontend:
    build:
      context: itv-frontend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
    links:
      - itv-mongo
    volumes:
      - /mnt/disk1/share/tep-itv/site:/site/tep-itv
    stdin_open: true
    tty: true
  itv-vsftpd:
    build:
      context: itv-vsftpd
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"
    volumes:
      - ./vsftpd/home:/home/vsftpd
      - ./vsftpd/logs:/var/log/vsftpd    
      - /mnt/disk1/share/tep-itv/site:/site/tep-itv
      - /mnt/disk1/share/tep-paseka/site:/site/tep-paseka

volumes:
  itv-mongo-data:    

networks:
  default: